// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrdxaIimQ3MZcwUtyryVVBkdV76S73DNQ',
    appId: '1:227677038191:web:d99b89b69c086d80cb0f9a',
    messagingSenderId: '227677038191',
    projectId: 'stocktracker-cb0aa',
    authDomain: 'stocktracker-cb0aa.firebaseapp.com',
    storageBucket: 'stocktracker-cb0aa.firebasestorage.app',
    measurementId: 'G-GNKFWG8XQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwkB9V-Vz95fBB0JLJgrFYKu6BVOyQQhM',
    appId: '1:227677038191:android:a8770a638e1f949dcb0f9a',
    messagingSenderId: '227677038191',
    projectId: 'stocktracker-cb0aa',
    storageBucket: 'stocktracker-cb0aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkD-w3azlX0yi-wYvLxNoACkBKyrs2L7g',
    appId: '1:227677038191:ios:721202ddb8177699cb0f9a',
    messagingSenderId: '227677038191',
    projectId: 'stocktracker-cb0aa',
    storageBucket: 'stocktracker-cb0aa.firebasestorage.app',
    iosBundleId: 'com.example.stockTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkD-w3azlX0yi-wYvLxNoACkBKyrs2L7g',
    appId: '1:227677038191:ios:721202ddb8177699cb0f9a',
    messagingSenderId: '227677038191',
    projectId: 'stocktracker-cb0aa',
    storageBucket: 'stocktracker-cb0aa.firebasestorage.app',
    iosBundleId: 'com.example.stockTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrdxaIimQ3MZcwUtyryVVBkdV76S73DNQ',
    appId: '1:227677038191:web:f4733a40941d3637cb0f9a',
    messagingSenderId: '227677038191',
    projectId: 'stocktracker-cb0aa',
    authDomain: 'stocktracker-cb0aa.firebaseapp.com',
    storageBucket: 'stocktracker-cb0aa.firebasestorage.app',
    measurementId: 'G-07TBNC4BHV',
  );
}
